### ISSUE TITLE
Mod Causes Items from Other Mods to Be Movable While GUIs Are Open

### ISSUE THREAD

**Issue by Darkosto** [kirderf1/InventoryFree#10]
**Describe the bug**
I initially reported this issue to the ProjectE devs, but after further investigation, it looks like InventoryFree is the cause. Items from mods that have a GUI (like the ProjectE tablet) are allowed to move the item despite its GUI being open. This is an issue that can cause duplication glitches and losing items depending on the circumstances. 

**To Reproduce**
1. Install ProjectE and InventoryFree
2. Open the ProjectE Tablet
3. Pick Up the tablet with the mouse

**Expected behavior**
Items that have GUIs should not be allowed to move once it is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/10309699/167195843-208be6c8-ed94-41c8-8a1a-b4895025c349.png)

![image](https://user-images.githubusercontent.com/10309699/167195925-4efa9aac-71fb-4153-b9d9-dcd7fdca1910.png)

**Versions (please complete the following information):**
 - Forge version: 30.1.16
 - Mod Version: InventoryFree: 1.18.2-3.1.0, ProjectE: 1.0.1

**Additional context**
Here is the issue posted on the ProjectE issue page: https://github.com/sinkillerj/ProjectE/issues/2195

**Comment by pupnewfster** [comment]
After a brief glance at the code my best guess is it is because of [this](https://github.com/kirderf1/InventoryFree/blob/1.18/src/main/java/kirderf1/inventoryfree/BlockedSlot.java#L11)

**Comment by kirderf1** [comment]
Yeah, that's a serious problem.

I believe pupnewfsters guess is correct. As the blocked slot does not properly wrap around the replaced slot, it does not replicate extra restrictions (or some other things) in cases such as this.
