### ISSUE TITLE
[suggestion] Fabric port 1.20.1

### ISSUE THREAD

**Issue by CanecaKun** [kirderf1/InventoryFree#16]
**Is your feature request related to a problem? Please describe.**
Mod works exclusively on forge

**Describe the solution you'd like**
Fabric port for 1.20.1

**Describe alternatives you've considered**
Have considered using sinytra conectors but other mods don't work with that and also its bad for multiplayer so fabric is better

**Additional context**
No further context needed, fabric has a huge and ever growing player base, it would be great to have access to, and to help that public.

**Comment by kirderf1** [comment]
At the moment, this mod relies heavily on the events and systems provided by forge/neoforge. With the large degree of platform-specific code, I don't want to commit myself to turning this into a multi-platform mod or maintaining it as such at this current time.
