### ISSUE TITLE
(Suggestion) Better icon for locked slots

### ISSUE THREAD

**Issue by Winddbourne** [kirderf1/InventoryFree#4]
I've been really enjoying the mod and use it in both my Nightfall mod pack found here:

https://www.curseforge.com/minecraft/modpacks/nightfall2

And also in an upcoming pack I'm working on now. 

But I really wasn't a fan of the simple X so I created this lock Icon both to make it clear that these are locked slots, and also to be a bit more visually appealing. 

You don't have to use it but I thought I might as well upload the file as a suggestion for your next update:

![lock](https://user-images.githubusercontent.com/24589533/120085826-5996e780-c0a9-11eb-90ed-cae33ca2363d.png)

And a screenshot from inside the game:

![2021-05-29_20 16 46](https://user-images.githubusercontent.com/24589533/120088354-6d4c4900-c0bd-11eb-9f04-53c93dfb26df.png)

PS - the mod still works for 1.16.5 but only shows up in searches when you are working on a 1.16.4 pack so you might want to include both versions as supported when you do your next file update. :)

**Comment by kirderf1** [comment]
I think it's an improvement!
So with your permission to use the lock texture you made, I'll make include it next time I'll make an update

Also, I'll make sure to update metadata on existing files regarding 1.16.5, once I find the curseforge website to be back up

**Comment by Winddbourne** [comment]
Awesome! Glad I was able to help. :)

And I was having trouble accessing Curseforge too, but it seems to be back up for me now. I'll cross my fingers that its available to you as well.
