### ISSUE TITLE
[Feature request]Option to unlock inventory slots bottom up.

### ISSUE THREAD

**Issue by MisterObvious25** [kirderf1/InventoryFree#6]
Right now, the slots are unlocked in the following order

1. slots on the hotbar
2. slots top row - down in the inventory.

I would love it if there were a option that would allow the first row of the inventory to be unlocked(step 2) to be the one closest to the hotbar(so unlocking down-up, instead of the current behavior)

**Comment by kirderf1** [comment]
Right now, slots are unlocked in the same order that they're indexed in the inventory, which in turn is tied to things like item pickup slots or item shift-clicking. To change the order in which slots are unlocked would most likely cause some unwanted behaviors if done in isolation. While I'm sure that such unwanted can be circumvented or worked around, I don't think this feature would be important enough to try implementing that.

I'll leave this issue open for a bit of time in case someone else comes across this and want to try implementing it.
