### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Taknax** [kirderf1/InventoryFree#8]
Permanently locked hotbar slot.
I would like to lock the first hotbar slot permanently (So i have allways a free hand. Useful for some mods). So even the setted item for unlocking the other slots cant unlock the defined permanent locked slots.

I setted minecraft:emerald as unlock item but i could not figured out, what to do to unlock?

**Comment by kirderf1** [comment]
Such a feature suffers from the same limitation as #6, and as such is not compatible with how the mod currently enforces locked slots.
Check if the unlock item has a tooltip. If it does not, then it's likely not configured correctly.
